apiVersion: v1
kind: Secret
metadata:
  name: secret-sa-sample
  annotations:
    kubernetes.io/service-account.name: "sa-name"
type: kubernetes.io/service-account-token
data:
  extra: YmFyCg==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          # Secret can be mounted either as env or as volume mount
          env:
            - name: TEST_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-sa-sample
                  key: extra
          volumeMounts:
            - name: foo
              mountPath: "/etc/foo"
              readOnly: true
      volumes:
        - name: foo
          secret:
            secretName: secret-sa-sample
            optional: true
