apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-read-role
  namespace: ns2
rules:
  apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account-ns1
  namespace: ns1