apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fluntd
  name: fluntd
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluntd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fluntd
    spec:
      containers:
      - image: testimage
        name: testimage
        resources: {}
status: {}
